# -*- coding: utf-8 -*-
"""
/***************************************************************************
 FireToolbox
                                 A QGIS plugin
 A collection of fire insights related algorithms
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                              -------------------
        begin                : 2023-08-30
        copyright            : (C) 2023 by Fernando Badilla Veliz - Fire2a.com
        email                : fbadilla@ing.uchile.cl
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""

__author__ = "Fernando Badilla Veliz - Fire2a.com"
__date__ = "2023-08-30"
__copyright__ = "(C) 2023 by Fernando Badilla Veliz - Fire2a.com"
__revision__ = "$Format:%H$"


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load FireToolbox class from file FireToolbox.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    from . import dependencies_handler

    dependencies_handler.run()

    from platform import system as platform_system
    if platform_system() == "Windows":
        from .decision_optimization.doop import add_cbc_to_path, add_cplex_to_path
        from qgis.core import QgsMessageLog
        add_cbc_to_path(QgsMessageLog)
        add_cplex_to_path(QgsMessageLog)
    
     
    from .fireanalyticstoolbox import FireToolboxPlugin

    return FireToolboxPlugin()
